export type Lease = import("../bosdyn-client/lease").Lease;
export type KeyValue = import("../../src/bosdyn/api/mission/util_pb").KeyValue;
export type DictParam = import("../../src/bosdyn/api/service_customization_pb").DictParam;
/**
 * Client for the RemoteMission service.
 * @extends {BaseClient<RemoteMissionServiceClient>}
 */
export class RemoteClient extends BaseClient<RemoteMissionServiceClient> {
    static defaultServiceName: null;
    static serviceType: string;
    constructor();
    leaseProcessor: LeaseWalletRequestProcessor | null;
    updateFrom(other: any): void;
    /**
     * Establish a session.
     * @param {Lease[]} leases Array of lease protobufs to establish session with.
     * @param {KeyValue[]} [inputs=null] any inputs needed by the remote node.
     * @param {string[]} [leaseResources=DEFAULT_RESOURCES] Array of resource names to use from the lease wallet.
     * Only applied if no leases are provided.
     * @param {Object} [args] Extra arguments for controlling RPC details.
     * @returns {Promise<string>}
     */
    establishSession(leases?: Lease[], inputs?: KeyValue[], leaseResources?: string[], args?: Object): Promise<string>;
    /**
     * Tick the remote node.
     * @param {string} sessionId The session identifier
     * @param {Lease[]} leases Array of lease protobufs to use during the tick.
     * @param {KeyValue[]} inputs any inputs needed by the remote node.
     * @param {string[]} leaseResources  List of resource names to use from the lease wallet.
     * Only applied if no leases are provided.
     * @param {string} groupName Callbacks can be used to record data using Data Acquisition. The mission
     * can provide a hint to the callback with the current group, so that the data the callback
     * saves is correctly grouped with other data generated by the mission. The value may change during ticking.
     * @param {DictParam} params Parameters set by the client. Depending on the structure
     * of the mission, the value may change during ticking.
     * @param {Object} [args] Extra arguments for controlling RPC details.
     * @returns {Promise<remotePb.TickResponse>}
     */
    tick(sessionId: string, leases?: Lease[], inputs?: KeyValue[], leaseResources?: string[], groupName?: string, params?: DictParam, args?: Object): Promise<remotePb.TickResponse>;
    /**
     * Stop a node that was previously ticked
     * @param {string} sessionId Session ID as returned by the EstablishSessionResponse.
     * @param {Object} [args] Extra arguments for controlling RPC details.
     * @returns {Promise<remotePb.StopResponse>}
     */
    stop(sessionId: string, args?: Object): Promise<remotePb.StopResponse>;
    /**
     * End the session originally established by an EstablishSessionRequest.
     * @param {string} sessionId Session ID as returned by the EstablishSessionResponse.
     * @param {Object} [args] Extra arguments for controlling RPC details.
     * @returns {Promise<remotePb.TeardownSessionResponse>}
     */
    teardownSession(sessionId: string, args?: Object): Promise<remotePb.TeardownSessionResponse>;
    /**
     * Get information about the service itself, such as a custom parameter spec.
     * @param {Object} [args] Extra arguments for controlling RPC details.
     * @returns {Promise<remotePb.GetRemoteMissionServiceInfoResponse>}
     */
    getServiceInfo(args?: Object): Promise<remotePb.GetRemoteMissionServiceInfoResponse>;
    _buildEstablishSessionRequest(inputs: any, leases: any, leaseResources: any): remotePb.EstablishSessionRequest;
    _buildTickRequest(inputs: any, leases: any, sessionId: any, leaseResources: any, groupName?: null, params?: null): remotePb.TickRequest;
}
/**
 * @typedef {import('../bosdyn-client/lease').Lease} Lease
 * @typedef {import('../../src/bosdyn/api/mission/util_pb').KeyValue} KeyValue
 * @typedef {import('../../src/bosdyn/api/service_customization_pb').DictParam} DictParam
 */
/** Provided session ID was not valid on the server. */
export class InvalidSessionId extends ResponseError {
}
/** Missing required inputs. */
export class MissingInputs extends ResponseError {
}
/** Missing leases on required resources. */
export class MissingLeases extends ResponseError {
}
export function treeStatusFromTickStatus(tickStatus: any): number;
import { RemoteMissionServiceClient } from "../../src/bosdyn/api/mission/remote_service_grpc_pb";
import { BaseClient } from "../bosdyn-client/common";
import { LeaseWalletRequestProcessor } from "../bosdyn-client/lease";
import remotePb = require("../../src/bosdyn/api/mission/remote_pb");
import { ResponseError } from "../bosdyn-client/exceptions";
