// source: bosdyn/api/metrics_logging/metrics_logging_robot.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var bosdyn_api_data_buffer_pb = require('../../../bosdyn/api/data_buffer_pb.js');
goog.object.extend(proto, bosdyn_api_data_buffer_pb);
var bosdyn_api_header_pb = require('../../../bosdyn/api/header_pb.js');
goog.object.extend(proto, bosdyn_api_header_pb);
var bosdyn_api_parameter_pb = require('../../../bosdyn/api/parameter_pb.js');
goog.object.extend(proto, bosdyn_api_parameter_pb);
var bosdyn_api_metrics_logging_signed_proto_pb = require('../../../bosdyn/api/metrics_logging/signed_proto_pb.js');
goog.object.extend(proto, bosdyn_api_metrics_logging_signed_proto_pb);
goog.exportSymbol('proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotRequest', null, global);
goog.exportSymbol('proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotResponse', null, global);
goog.exportSymbol('proto.bosdyn.api.metrics_logging.GetMetricsRequest', null, global);
goog.exportSymbol('proto.bosdyn.api.metrics_logging.GetMetricsResponse', null, global);
goog.exportSymbol('proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeRequest', null, global);
goog.exportSymbol('proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeRequest.displayName = 'proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeResponse.displayName = 'proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotRequest.repeatedFields_, null);
};
goog.inherits(proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotRequest.displayName = 'proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotResponse.repeatedFields_, null);
};
goog.inherits(proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotResponse.displayName = 'proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bosdyn.api.metrics_logging.GetMetricsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.bosdyn.api.metrics_logging.GetMetricsRequest.repeatedFields_, null);
};
goog.inherits(proto.bosdyn.api.metrics_logging.GetMetricsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bosdyn.api.metrics_logging.GetMetricsRequest.displayName = 'proto.bosdyn.api.metrics_logging.GetMetricsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bosdyn.api.metrics_logging.GetMetricsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.bosdyn.api.metrics_logging.GetMetricsResponse.repeatedFields_, null);
};
goog.inherits(proto.bosdyn.api.metrics_logging.GetMetricsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bosdyn.api.metrics_logging.GetMetricsResponse.displayName = 'proto.bosdyn.api.metrics_logging.GetMetricsResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    header: (f = msg.getHeader()) && bosdyn_api_header_pb.RequestHeader.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeRequest}
 */
proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeRequest;
  return proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeRequest}
 */
proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new bosdyn_api_header_pb.RequestHeader;
      reader.readMessage(value,bosdyn_api_header_pb.RequestHeader.deserializeBinaryFromReader);
      msg.setHeader(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeader();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      bosdyn_api_header_pb.RequestHeader.serializeBinaryToWriter
    );
  }
};


/**
 * optional bosdyn.api.RequestHeader header = 1;
 * @return {?proto.bosdyn.api.RequestHeader}
 */
proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeRequest.prototype.getHeader = function() {
  return /** @type{?proto.bosdyn.api.RequestHeader} */ (
    jspb.Message.getWrapperField(this, bosdyn_api_header_pb.RequestHeader, 1));
};


/**
 * @param {?proto.bosdyn.api.RequestHeader|undefined} value
 * @return {!proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeRequest} returns this
*/
proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeRequest.prototype.setHeader = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeRequest} returns this
 */
proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeRequest.prototype.clearHeader = function() {
  return this.setHeader(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeRequest.prototype.hasHeader = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    header: (f = msg.getHeader()) && bosdyn_api_header_pb.ResponseHeader.toObject(includeInstance, f),
    firstSequenceNumber: jspb.Message.getFieldWithDefault(msg, 2, 0),
    lastSequenceNumber: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeResponse}
 */
proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeResponse;
  return proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeResponse}
 */
proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new bosdyn_api_header_pb.ResponseHeader;
      reader.readMessage(value,bosdyn_api_header_pb.ResponseHeader.deserializeBinaryFromReader);
      msg.setHeader(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFirstSequenceNumber(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLastSequenceNumber(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeader();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      bosdyn_api_header_pb.ResponseHeader.serializeBinaryToWriter
    );
  }
  f = message.getFirstSequenceNumber();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getLastSequenceNumber();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * optional bosdyn.api.ResponseHeader header = 1;
 * @return {?proto.bosdyn.api.ResponseHeader}
 */
proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeResponse.prototype.getHeader = function() {
  return /** @type{?proto.bosdyn.api.ResponseHeader} */ (
    jspb.Message.getWrapperField(this, bosdyn_api_header_pb.ResponseHeader, 1));
};


/**
 * @param {?proto.bosdyn.api.ResponseHeader|undefined} value
 * @return {!proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeResponse} returns this
*/
proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeResponse.prototype.setHeader = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeResponse} returns this
 */
proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeResponse.prototype.clearHeader = function() {
  return this.setHeader(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeResponse.prototype.hasHeader = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int32 first_sequence_number = 2;
 * @return {number}
 */
proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeResponse.prototype.getFirstSequenceNumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeResponse} returns this
 */
proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeResponse.prototype.setFirstSequenceNumber = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 last_sequence_number = 3;
 * @return {number}
 */
proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeResponse.prototype.getLastSequenceNumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeResponse} returns this
 */
proto.bosdyn.api.metrics_logging.GetStoreSequenceRangeResponse.prototype.setLastSequenceNumber = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotRequest.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    header: (f = msg.getHeader()) && bosdyn_api_header_pb.RequestHeader.toObject(includeInstance, f),
    sequenceNumbersList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotRequest}
 */
proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotRequest;
  return proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotRequest}
 */
proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new bosdyn_api_header_pb.RequestHeader;
      reader.readMessage(value,bosdyn_api_header_pb.RequestHeader.deserializeBinaryFromReader);
      msg.setHeader(value);
      break;
    case 2:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt32() : [reader.readInt32()]);
      for (var i = 0; i < values.length; i++) {
        msg.addSequenceNumbers(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeader();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      bosdyn_api_header_pb.RequestHeader.serializeBinaryToWriter
    );
  }
  f = message.getSequenceNumbersList();
  if (f.length > 0) {
    writer.writePackedInt32(
      2,
      f
    );
  }
};


/**
 * optional bosdyn.api.RequestHeader header = 1;
 * @return {?proto.bosdyn.api.RequestHeader}
 */
proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotRequest.prototype.getHeader = function() {
  return /** @type{?proto.bosdyn.api.RequestHeader} */ (
    jspb.Message.getWrapperField(this, bosdyn_api_header_pb.RequestHeader, 1));
};


/**
 * @param {?proto.bosdyn.api.RequestHeader|undefined} value
 * @return {!proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotRequest} returns this
*/
proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotRequest.prototype.setHeader = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotRequest} returns this
 */
proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotRequest.prototype.clearHeader = function() {
  return this.setHeader(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotRequest.prototype.hasHeader = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated int32 sequence_numbers = 2;
 * @return {!Array<number>}
 */
proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotRequest.prototype.getSequenceNumbersList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotRequest} returns this
 */
proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotRequest.prototype.setSequenceNumbersList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotRequest} returns this
 */
proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotRequest.prototype.addSequenceNumbers = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotRequest} returns this
 */
proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotRequest.prototype.clearSequenceNumbersList = function() {
  return this.setSequenceNumbersList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotResponse.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    header: (f = msg.getHeader()) && bosdyn_api_header_pb.ResponseHeader.toObject(includeInstance, f),
    snapshotsList: jspb.Message.toObjectList(msg.getSnapshotsList(),
    bosdyn_api_metrics_logging_signed_proto_pb.SignedProto.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotResponse}
 */
proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotResponse;
  return proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotResponse}
 */
proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new bosdyn_api_header_pb.ResponseHeader;
      reader.readMessage(value,bosdyn_api_header_pb.ResponseHeader.deserializeBinaryFromReader);
      msg.setHeader(value);
      break;
    case 2:
      var value = new bosdyn_api_metrics_logging_signed_proto_pb.SignedProto;
      reader.readMessage(value,bosdyn_api_metrics_logging_signed_proto_pb.SignedProto.deserializeBinaryFromReader);
      msg.addSnapshots(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeader();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      bosdyn_api_header_pb.ResponseHeader.serializeBinaryToWriter
    );
  }
  f = message.getSnapshotsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      bosdyn_api_metrics_logging_signed_proto_pb.SignedProto.serializeBinaryToWriter
    );
  }
};


/**
 * optional bosdyn.api.ResponseHeader header = 1;
 * @return {?proto.bosdyn.api.ResponseHeader}
 */
proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotResponse.prototype.getHeader = function() {
  return /** @type{?proto.bosdyn.api.ResponseHeader} */ (
    jspb.Message.getWrapperField(this, bosdyn_api_header_pb.ResponseHeader, 1));
};


/**
 * @param {?proto.bosdyn.api.ResponseHeader|undefined} value
 * @return {!proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotResponse} returns this
*/
proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotResponse.prototype.setHeader = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotResponse} returns this
 */
proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotResponse.prototype.clearHeader = function() {
  return this.setHeader(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotResponse.prototype.hasHeader = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated SignedProto snapshots = 2;
 * @return {!Array<!proto.bosdyn.api.metrics_logging.SignedProto>}
 */
proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotResponse.prototype.getSnapshotsList = function() {
  return /** @type{!Array<!proto.bosdyn.api.metrics_logging.SignedProto>} */ (
    jspb.Message.getRepeatedWrapperField(this, bosdyn_api_metrics_logging_signed_proto_pb.SignedProto, 2));
};


/**
 * @param {!Array<!proto.bosdyn.api.metrics_logging.SignedProto>} value
 * @return {!proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotResponse} returns this
*/
proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotResponse.prototype.setSnapshotsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.bosdyn.api.metrics_logging.SignedProto=} opt_value
 * @param {number=} opt_index
 * @return {!proto.bosdyn.api.metrics_logging.SignedProto}
 */
proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotResponse.prototype.addSnapshots = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.bosdyn.api.metrics_logging.SignedProto, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotResponse} returns this
 */
proto.bosdyn.api.metrics_logging.GetAbsoluteMetricSnapshotResponse.prototype.clearSnapshotsList = function() {
  return this.setSnapshotsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.bosdyn.api.metrics_logging.GetMetricsRequest.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bosdyn.api.metrics_logging.GetMetricsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.bosdyn.api.metrics_logging.GetMetricsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bosdyn.api.metrics_logging.GetMetricsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bosdyn.api.metrics_logging.GetMetricsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    header: (f = msg.getHeader()) && bosdyn_api_header_pb.RequestHeader.toObject(includeInstance, f),
    keysList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f,
    includeEvents: jspb.Message.getBooleanFieldWithDefault(msg, 3, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bosdyn.api.metrics_logging.GetMetricsRequest}
 */
proto.bosdyn.api.metrics_logging.GetMetricsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bosdyn.api.metrics_logging.GetMetricsRequest;
  return proto.bosdyn.api.metrics_logging.GetMetricsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bosdyn.api.metrics_logging.GetMetricsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bosdyn.api.metrics_logging.GetMetricsRequest}
 */
proto.bosdyn.api.metrics_logging.GetMetricsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new bosdyn_api_header_pb.RequestHeader;
      reader.readMessage(value,bosdyn_api_header_pb.RequestHeader.deserializeBinaryFromReader);
      msg.setHeader(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addKeys(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIncludeEvents(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bosdyn.api.metrics_logging.GetMetricsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bosdyn.api.metrics_logging.GetMetricsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bosdyn.api.metrics_logging.GetMetricsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bosdyn.api.metrics_logging.GetMetricsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeader();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      bosdyn_api_header_pb.RequestHeader.serializeBinaryToWriter
    );
  }
  f = message.getKeysList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = message.getIncludeEvents();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
};


/**
 * optional bosdyn.api.RequestHeader header = 1;
 * @return {?proto.bosdyn.api.RequestHeader}
 */
proto.bosdyn.api.metrics_logging.GetMetricsRequest.prototype.getHeader = function() {
  return /** @type{?proto.bosdyn.api.RequestHeader} */ (
    jspb.Message.getWrapperField(this, bosdyn_api_header_pb.RequestHeader, 1));
};


/**
 * @param {?proto.bosdyn.api.RequestHeader|undefined} value
 * @return {!proto.bosdyn.api.metrics_logging.GetMetricsRequest} returns this
*/
proto.bosdyn.api.metrics_logging.GetMetricsRequest.prototype.setHeader = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bosdyn.api.metrics_logging.GetMetricsRequest} returns this
 */
proto.bosdyn.api.metrics_logging.GetMetricsRequest.prototype.clearHeader = function() {
  return this.setHeader(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bosdyn.api.metrics_logging.GetMetricsRequest.prototype.hasHeader = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated string keys = 2;
 * @return {!Array<string>}
 */
proto.bosdyn.api.metrics_logging.GetMetricsRequest.prototype.getKeysList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.bosdyn.api.metrics_logging.GetMetricsRequest} returns this
 */
proto.bosdyn.api.metrics_logging.GetMetricsRequest.prototype.setKeysList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.bosdyn.api.metrics_logging.GetMetricsRequest} returns this
 */
proto.bosdyn.api.metrics_logging.GetMetricsRequest.prototype.addKeys = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.bosdyn.api.metrics_logging.GetMetricsRequest} returns this
 */
proto.bosdyn.api.metrics_logging.GetMetricsRequest.prototype.clearKeysList = function() {
  return this.setKeysList([]);
};


/**
 * optional bool include_events = 3;
 * @return {boolean}
 */
proto.bosdyn.api.metrics_logging.GetMetricsRequest.prototype.getIncludeEvents = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.bosdyn.api.metrics_logging.GetMetricsRequest} returns this
 */
proto.bosdyn.api.metrics_logging.GetMetricsRequest.prototype.setIncludeEvents = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.bosdyn.api.metrics_logging.GetMetricsResponse.repeatedFields_ = [2,3,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bosdyn.api.metrics_logging.GetMetricsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.bosdyn.api.metrics_logging.GetMetricsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bosdyn.api.metrics_logging.GetMetricsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bosdyn.api.metrics_logging.GetMetricsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    header: (f = msg.getHeader()) && bosdyn_api_header_pb.ResponseHeader.toObject(includeInstance, f),
    parametersList: jspb.Message.toObjectList(msg.getParametersList(),
    bosdyn_api_parameter_pb.Parameter.toObject, includeInstance),
    missingKeysList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
    eventsList: jspb.Message.toObjectList(msg.getEventsList(),
    bosdyn_api_data_buffer_pb.Event.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bosdyn.api.metrics_logging.GetMetricsResponse}
 */
proto.bosdyn.api.metrics_logging.GetMetricsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bosdyn.api.metrics_logging.GetMetricsResponse;
  return proto.bosdyn.api.metrics_logging.GetMetricsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bosdyn.api.metrics_logging.GetMetricsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bosdyn.api.metrics_logging.GetMetricsResponse}
 */
proto.bosdyn.api.metrics_logging.GetMetricsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new bosdyn_api_header_pb.ResponseHeader;
      reader.readMessage(value,bosdyn_api_header_pb.ResponseHeader.deserializeBinaryFromReader);
      msg.setHeader(value);
      break;
    case 2:
      var value = new bosdyn_api_parameter_pb.Parameter;
      reader.readMessage(value,bosdyn_api_parameter_pb.Parameter.deserializeBinaryFromReader);
      msg.addParameters(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addMissingKeys(value);
      break;
    case 4:
      var value = new bosdyn_api_data_buffer_pb.Event;
      reader.readMessage(value,bosdyn_api_data_buffer_pb.Event.deserializeBinaryFromReader);
      msg.addEvents(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bosdyn.api.metrics_logging.GetMetricsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bosdyn.api.metrics_logging.GetMetricsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bosdyn.api.metrics_logging.GetMetricsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bosdyn.api.metrics_logging.GetMetricsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeader();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      bosdyn_api_header_pb.ResponseHeader.serializeBinaryToWriter
    );
  }
  f = message.getParametersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      bosdyn_api_parameter_pb.Parameter.serializeBinaryToWriter
    );
  }
  f = message.getMissingKeysList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = message.getEventsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      bosdyn_api_data_buffer_pb.Event.serializeBinaryToWriter
    );
  }
};


/**
 * optional bosdyn.api.ResponseHeader header = 1;
 * @return {?proto.bosdyn.api.ResponseHeader}
 */
proto.bosdyn.api.metrics_logging.GetMetricsResponse.prototype.getHeader = function() {
  return /** @type{?proto.bosdyn.api.ResponseHeader} */ (
    jspb.Message.getWrapperField(this, bosdyn_api_header_pb.ResponseHeader, 1));
};


/**
 * @param {?proto.bosdyn.api.ResponseHeader|undefined} value
 * @return {!proto.bosdyn.api.metrics_logging.GetMetricsResponse} returns this
*/
proto.bosdyn.api.metrics_logging.GetMetricsResponse.prototype.setHeader = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bosdyn.api.metrics_logging.GetMetricsResponse} returns this
 */
proto.bosdyn.api.metrics_logging.GetMetricsResponse.prototype.clearHeader = function() {
  return this.setHeader(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bosdyn.api.metrics_logging.GetMetricsResponse.prototype.hasHeader = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated bosdyn.api.Parameter parameters = 2;
 * @return {!Array<!proto.bosdyn.api.Parameter>}
 */
proto.bosdyn.api.metrics_logging.GetMetricsResponse.prototype.getParametersList = function() {
  return /** @type{!Array<!proto.bosdyn.api.Parameter>} */ (
    jspb.Message.getRepeatedWrapperField(this, bosdyn_api_parameter_pb.Parameter, 2));
};


/**
 * @param {!Array<!proto.bosdyn.api.Parameter>} value
 * @return {!proto.bosdyn.api.metrics_logging.GetMetricsResponse} returns this
*/
proto.bosdyn.api.metrics_logging.GetMetricsResponse.prototype.setParametersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.bosdyn.api.Parameter=} opt_value
 * @param {number=} opt_index
 * @return {!proto.bosdyn.api.Parameter}
 */
proto.bosdyn.api.metrics_logging.GetMetricsResponse.prototype.addParameters = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.bosdyn.api.Parameter, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.bosdyn.api.metrics_logging.GetMetricsResponse} returns this
 */
proto.bosdyn.api.metrics_logging.GetMetricsResponse.prototype.clearParametersList = function() {
  return this.setParametersList([]);
};


/**
 * repeated string missing_keys = 3;
 * @return {!Array<string>}
 */
proto.bosdyn.api.metrics_logging.GetMetricsResponse.prototype.getMissingKeysList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.bosdyn.api.metrics_logging.GetMetricsResponse} returns this
 */
proto.bosdyn.api.metrics_logging.GetMetricsResponse.prototype.setMissingKeysList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.bosdyn.api.metrics_logging.GetMetricsResponse} returns this
 */
proto.bosdyn.api.metrics_logging.GetMetricsResponse.prototype.addMissingKeys = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.bosdyn.api.metrics_logging.GetMetricsResponse} returns this
 */
proto.bosdyn.api.metrics_logging.GetMetricsResponse.prototype.clearMissingKeysList = function() {
  return this.setMissingKeysList([]);
};


/**
 * repeated bosdyn.api.Event events = 4;
 * @return {!Array<!proto.bosdyn.api.Event>}
 */
proto.bosdyn.api.metrics_logging.GetMetricsResponse.prototype.getEventsList = function() {
  return /** @type{!Array<!proto.bosdyn.api.Event>} */ (
    jspb.Message.getRepeatedWrapperField(this, bosdyn_api_data_buffer_pb.Event, 4));
};


/**
 * @param {!Array<!proto.bosdyn.api.Event>} value
 * @return {!proto.bosdyn.api.metrics_logging.GetMetricsResponse} returns this
*/
proto.bosdyn.api.metrics_logging.GetMetricsResponse.prototype.setEventsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.bosdyn.api.Event=} opt_value
 * @param {number=} opt_index
 * @return {!proto.bosdyn.api.Event}
 */
proto.bosdyn.api.metrics_logging.GetMetricsResponse.prototype.addEvents = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.bosdyn.api.Event, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.bosdyn.api.metrics_logging.GetMetricsResponse} returns this
 */
proto.bosdyn.api.metrics_logging.GetMetricsResponse.prototype.clearEventsList = function() {
  return this.setEventsList([]);
};


goog.object.extend(exports, proto.bosdyn.api.metrics_logging);
