/**
 * @file Helpers for the data acquisition service: acquisition requests, their cancellation, and the download of the
 * acquired data from the REST API of the robot.
 */

'use strict';

const { createWriteStream, mkdirSync } = require('node:fs');
const path = require('node:path');
const process = require('node:process');
const { Transform } = require('node:stream');
const { pipeline } = require('node:stream/promises');
const { setTimeout: sleep } = require('node:timers/promises');

const { Timestamp } = require('google-protobuf/google/protobuf/timestamp_pb');

const { ResponseError } = require('./exceptions');
const { httpsGetUnverified } = require('./util');

const dataAcquisitionPb = require('../bosdyn/api/data_acquisition_pb');
const dataAcquisitionStorePb = require('../bosdyn/api/data_acquisition_store_pb');

/**
 * @typedef {import('./data_acquisition').DataAcquisitionClient} DataAcquisitionClient
 * @typedef {import('./data_acquisition_store').DataAcquisitionStoreClient} DataAcquisitionStoreClient
 * @typedef {import('./exceptions').RpcError} RpcError
 * @typedef {import('./robot').Robot} Robot
 */

/**
 * Name of a value of a proto enum, like Python's Status.Name().
 * @param {Object<string, number>} enumObject
 * @param {number} value
 * @returns {string}
 */
function _enumName(enumObject, value) {
  return Object.keys(enumObject).find(key => enumObject[key] === value) ?? String(value);
}

/**
 * Sends the data acquisition request without blocking until the acquisition completes.
 * @param {DataAcquisitionClient} dataAcqClient DataAcquisition client for send the acquisition requests.
 * @param {*} acquisitionRequests Acquisition requests to include in request message.
 * @param {string} groupName Group name for the acquisitions.
 * @param {string} actionName Action name for the acquisitions.
 * @param {dataAcquisitionPb.Metadata} metadata Metadata to include in the request message.
 * @param {*} dataTimestamp Timestamp to use for the acquisitions. If None the timestamp will be
 * generated by the data acquisition client.
 * @returns {Promise<{ requestId: number, actionId: dataAcquisitionPb.CaptureActionId }>} A request id set as null
 * indicates the AcquireData rpc failed.
 * @throws {RpcError} Problem communicating with the robot.
 */
async function issueAcquireDataRequest(
  dataAcqClient,
  acquisitionRequests,
  groupName,
  actionName,
  metadata = null,
  dataTimestamp = null,
) {
  const actionId = new dataAcquisitionPb.CaptureActionId()
    .setActionName(actionName)
    .setGroupName(groupName)
    .setTimestamp(dataTimestamp);
  let requestId = null;

  try {
    requestId = await dataAcqClient.acquireData(
      acquisitionRequests,
      actionName,
      actionId.getGroupName(),
      dataTimestamp,
      metadata,
    );
  } catch (e) {
    // Like Python, only the errors of the response: the RPC errors reach the caller.
    if (!(e instanceof ResponseError)) throw e;
    console.error(`[DATA ACQUISITION HELPERS] Exception raised by issueAcquireDataRequest: ${e}`);
  }

  return { requestId, actionId };
}

/**
 * Send acquisition request and optionally block until the acquisition completes.
 * If blocking, the GetStatus RPC is used to monitor the status of the acquisition request.
 * @param {DataAcquisitionClient} dataAcquisitionClient The client for send the acquisition requests.
 * @param {dataAcquisitionPb.AcquisitionRequestList} acquisitionRequests Acquisition requests
 * to include in request message.
 * @param {string} groupName Group name for the acquisitions.
 * @param {string} actionName Action name for the acquisitions.
 * @param {dataAcquisitionPb.Metadata} metadata Metadata to include in the request message.
 * @param {boolean} blockUntilComplete If true, don't return until the GetStatus completes.
 * @param {*} dataTimestamp Timestamp to use for the acquisitions. If None the timestamp will be
            generated by the data acquisition client.
 * @returns {Promise<boolean>} Whether the acquisition completed successfully.
 * @throws {RpcError} Problem communicating with the robot.
 */
async function acquireAndProcessRequest(
  dataAcquisitionClient,
  acquisitionRequests,
  groupName,
  actionName,
  metadata = null,
  blockUntilComplete = true,
  dataTimestamp = null,
) {
  const { requestId } = await issueAcquireDataRequest(
    dataAcquisitionClient,
    acquisitionRequests,
    groupName,
    actionName,
    metadata,
    dataTimestamp,
  );

  if (!requestId) return false;

  if (!blockUntilComplete) return true;

  const { Status } = dataAcquisitionPb.GetStatusResponse;
  console.log(`[DATA ACQUISITION HELPERS] Waiting for acquisition (id: ${requestId}) to complete.`);

  for (;;) {
    let getStatusResponse = null;
    try {
      getStatusResponse = await dataAcquisitionClient.getStatus(requestId);
    } catch (e) {
      if (!(e instanceof ResponseError)) throw e;
      console.error(`[DATA ACQUISITION HELPERS] Exception: ${e}`);
      return false;
    }
    const status = getStatusResponse.getStatus();
    const details = JSON.stringify(getStatusResponse.toObject());
    console.log(`[DATA ACQUISITION HELPERS] Current status is: ${_enumName(Status, status)}`);
    if (status === Status.STATUS_COMPLETE) {
      return true;
    }
    if (status === Status.STATUS_TIMEDOUT) {
      console.log(`[DATA ACQUISITION HELPERS] Unrecoverable request timeout: ${details}`);
      return false;
    }
    if (status === Status.STATUS_DATA_ERROR) {
      console.log(`[DATA ACQUISITION HELPERS] Data error was received: ${details}`);
      return false;
    }
    if (status === Status.STATUS_REQUEST_ID_DOES_NOT_EXIST) {
      console.log(`[DATA ACQUISITION HELPERS] The acquisition request id "${requestId}" is unknown: ${details}`);
      return false;
    }
    // A timer that keeps the process alive, like the time.sleep() of Python: an unref'd one let it exit.
    await sleep(200);
  }
}

/**
 * Cancels an acquisition request based on the request id
 * @param {DataAcquisitionClient} dataAcqClient DataAcquisition client for send the acquisition requests.
 * @param {number} requestId The id number for the AcquireData request to cancel.
 * @returns {Promise<void>}
 * @throws {RpcError} Problem communicating with the robot.
 */
async function cancelAcquisitionRequest(dataAcqClient, requestId) {
  if (!requestId) return;

  try {
    const isCancelledResponse = await dataAcqClient.cancelAcquisition(requestId);
    console.log(
      `[DATA ACQUISITION HELPERS] Status of the request to cancel the data-acquisition in progress: ${_enumName(
        dataAcquisitionPb.CancelAcquisitionResponse.Status,
        isCancelledResponse.getStatus(),
      )}`,
    );
  } catch (e) {
    if (!(e instanceof ResponseError)) throw e;
    console.error(`[DATA ACQUISITION HELPERS] ResponseError raised when cancelling: ${e}`);
    return;
  }

  const { Status } = dataAcquisitionPb.GetStatusResponse;

  for (;;) {
    let getStatusResponse = null;
    try {
      getStatusResponse = await dataAcqClient.getStatus(requestId);
    } catch (e) {
      if (!(e instanceof ResponseError)) throw e;
      console.error(`[DATA ACQUISITION HELPERS] Exception: ${e}`);
      break;
    }

    console.log(
      `[DATA ACQUISITION HELPERS] Request ${requestId} status: ${_enumName(Status, getStatusResponse.getStatus())}`,
    );
    if (getStatusResponse.getStatus() === Status.STATUS_ACQUISITION_CANCELLED) {
      console.log('[DATA ACQUISITION HELPERS] The request is fully cancelled.');
      break;
    }
  }
}

/**
 * Removes bad characters in a filename.
 * @param {string} filename Original filename to clean.
 * @returns {string}
 * @private
 */
function cleanFilename(filename) {
  return filename.replaceAll(/[:*?<>|]/gi, '');
}

/**
 * Create time-based query params for the download request.
 * @param {number} startTimeSecs The start time for the download data range.
 * @param {number} endTimeSecs The end time for the download range.
 * @param {Robot} robot The robot object, used to acquire timesync and convert the
 * times to robot time.
 * @returns {Promise<dataAcquisitionStorePb.DataQueryParams>}
 */
async function makeTimeQueryParams(startTimeSecs, endTimeSecs, robot) {
  const fromTimestamp = await (await robot.timeSync).robotTimestampFromLocalSecs(startTimeSecs);
  const toTimestamp = await (await robot.timeSync).robotTimestampFromLocalSecs(endTimeSecs);
  const timeRange = new dataAcquisitionStorePb.TimeRangeQuery()
    .setFromTimestamp(fromTimestamp)
    .setToTimestamp(toTimestamp);
  return new dataAcquisitionStorePb.DataQueryParams().setTimeRange(timeRange);
}

/**
 * Create time-based query params for the download request using the group name.
 * @param {string} groupName The group name for the data to be downloaded.
 * @param {DataAcquisitionStoreClient} dataStoreClient The data store client, used to get the action
 * ids for the group name.
 * @returns {Promise<dataAcquisitionStorePb.DataQueryParams|null>}
 */
async function makeTimeQueryParamsFromGroupName(groupName, dataStoreClient) {
  const actionId = new dataAcquisitionPb.CaptureActionId().setGroupName(groupName);
  // addActionIds() returns the added CaptureActionId, not the ActionIdQuery.
  const actionIds = new dataAcquisitionStorePb.ActionIdQuery().setActionIdsList([actionId]);
  const queryParams = new dataAcquisitionStorePb.DataQueryParams().setActionIds(actionIds);
  let savedCaptureActions = [];
  try {
    savedCaptureActions = await dataStoreClient.listCaptureActions(queryParams);
  } catch (e) {
    console.error(`[DATA ACQUISITION HELPERS] Failed to list the capture action ids for group_name ${groupName}: ${e}`);
    return null;
  }

  // Filter all the CaptureActionIds for the start/end time. These end times are already in
  // the robots clock and do not need to be converted using timesync.
  let startTime = [null, null];
  let endTime = [null, null];
  for (const saveCapture of savedCaptureActions) {
    const timestamp = saveCapture.getTimestamp() ?? new Timestamp();
    const timeSecs = timestamp.getSeconds() + timestamp.getNanos() / 1e9;

    // The plugin captures don't seem to set a timestamp, so ignore them when determining
    // the start/end times for what to download.
    if (timeSecs === 0) continue;

    if (startTime[0] === null || timeSecs < startTime[0]) {
      startTime = [timeSecs, timestamp];
    }
    if (endTime[0] === null || timeSecs > endTime[0]) {
      endTime = [timeSecs, timestamp];
    }
  }

  if (startTime[0] === null && endTime[0] === null) {
    // eslint-disable-next-line
    console.error(`[DATA ACQUISITION HELPERS] Could not find a start/end time from the list of capture action ids: ${JSON.stringify(savedCaptureActions.map(action => action.toObject()))}`);
    return null;
  }

  console.assert(startTime[0] <= endTime[0]);

  // Adjust the start/end time by a few seconds each to give buffer room. Copies: with a single capture action,
  // the start and the end are the same timestamp, and the listed capture actions stay as they are.
  const fromTimestamp = startTime[1].clone().setSeconds(startTime[1].getSeconds() - 3);
  const toTimestamp = endTime[1].clone().setSeconds(endTime[1].getSeconds() + 3);

  // eslint-disable-next-line
  console.info(`[DATA ACQUISITION HELPERS] Downloading data with a start time of ${startTime[0]} seconds and end time of ${endTime[0]} seconds.`);

  const timeRange = new dataAcquisitionStorePb.TimeRangeQuery()
    .setFromTimestamp(fromTimestamp)
    .setToTimestamp(toTimestamp);
  return new dataAcquisitionStorePb.DataQueryParams().setTimeRange(timeRange);
}

/**
 * Nanoseconds of a timestamp, like Timestamp.ToNanoseconds() in Python: a BigInt, since the nanoseconds since the
 * epoch are above Number.MAX_SAFE_INTEGER.
 * @param {?Timestamp} timestamp
 * @returns {bigint}
 */
function _timestampToNanoseconds(timestamp) {
  return timestamp ? BigInt(timestamp.getSeconds()) * 1_000_000_000n + BigInt(timestamp.getNanos()) : 0n;
}

/** Size of the chunks the download is printed with, like the chunks of the Python download. */
const DOWNLOAD_CHUNK_SIZE = 10 * 1024 ** 2;

/**
 * A stream that prints a dot for each chunk of the download, like the Python download.
 * @returns {Transform}
 */
function _downloadProgress() {
  let received = 0;
  return new Transform({
    transform(chunk, encoding, callback) {
      const before = Math.ceil(received / DOWNLOAD_CHUNK_SIZE);
      received += chunk.length;
      process.stdout.write('.'.repeat(Math.ceil(received / DOWNLOAD_CHUNK_SIZE) - before));
      callback(null, chunk);
    },
  });
}

/**
 * Retrieve all data for a query from the DataBuffer REST API and write it to files.
 * Like Python, the certificate of the robot is not checked.
 * @param {dataAcquisitionStorePb.DataQueryParams} queryParams Query parameters to use to
 * retrieve metadata from the DataStore service. Must be time-based query parameters only.
 * @param {string} hostname Hostname to specify in URL where the DataBuffer service is running.
 * @param {string} token User token to specify in https GET request for authentication.
 * @param {string} destinationFolder Folder where to download the data.
 * @param {?Object<string, *>} additionalParams Additional GET parameters to append to the URL.
 * @returns {Promise<boolean>} Boolean indicating if the data was downloaded successfully or not.
 */
async function downloadDataREST(queryParams, hostname, token, destinationFolder = '.', additionalParams = null) {
  try {
    const url = `https://${hostname}/v1/data-buffer/daq-data/`;
    const absolutePath = path.resolve(destinationFolder);
    const folder = path.join(path.dirname(absolutePath), cleanFilename(path.basename(absolutePath)), 'REST');
    mkdirSync(folder, { recursive: true });

    const headers = { Authorization: `Bearer ${token}` };
    const getParams = { ...additionalParams };
    if (queryParams.hasTimeRange()) {
      getParams.from_nsec = _timestampToNanoseconds(queryParams.getTimeRange().getFromTimestamp());
      getParams.to_nsec = _timestampToNanoseconds(queryParams.getTimeRange().getToTimestamp());
    }

    const resp = await httpsGetUnverified(`${url}?${new URLSearchParams(getParams)}`, headers);
    if (resp.statusCode >= 400) {
      // urlopen() raises an HTTPError in Python.
      resp.resume();
      console.log('[DATA ACQUISITION HELPERS] REST Exception:\n');
      console.log(`HTTP Error ${resp.statusCode}: ${resp.statusMessage}`);
      return false;
    }
    console.log(`[DATA ACQUISITION HELPERS] Download request HTTPS status code: ${resp.statusCode}`);
    if (resp.statusCode === 204) {
      resp.resume();
      const [from, to] = [getParams.from_nsec, getParams.to_nsec].map(nsec => Math.trunc(Number(nsec ?? 0n) / 1e9));

      console.log(
        `[DATA ACQUISITION HELPERS] No content available for the specified download time range (in seconds): [${from}, ${to}]`,
      );
      return false;
    }

    // This is the default file name used to download data, updated from response.
    let downloadFile = path.join(folder, 'download.zip');
    const content = resp.headers['content-disposition'];
    if (!content || content.length < 2) {
      resp.resume();
      console.log('[DATA ACQUISITION HELPERS] ERROR: Content-Disposition is not set correctly');
      return false;
    }
    const startInd = content.indexOf('"');
    if (startInd === -1) {
      resp.resume();
      console.error('[DATA ACQUISITION HELPERS] ERROR: Content-Disposition does not have a " character');
      return false;
    }
    // Only a file name: the file stays in the folder.
    downloadFile = path.join(folder, cleanFilename(path.basename(content.slice(startInd + 1, -1))));

    // The data is written while it is received (it was kept in memory).
    await pipeline(resp, _downloadProgress(), createWriteStream(downloadFile));
  } catch (e) {
    // The IOError of Python: a file that can not be created or written.
    const io = ['open', 'write', 'mkdir', 'close'].includes(e?.syscall);
    console.log(`[DATA ACQUISITION HELPERS] ${io ? 'IO' : 'REST'} Exception:\n`);
    console.log(e);
    return false;
  }
  // Data downloaded and saved to local disc successfully.
  return true;
}

module.exports = {
  issueAcquireDataRequest,
  acquireAndProcessRequest,
  cancelAcquisitionRequest,
  cleanFilename,
  makeTimeQueryParams,
  makeTimeQueryParamsFromGroupName,
  downloadDataREST,
};
