// source: bosdyn/api/units.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

goog.exportSymbol('proto.bosdyn.api.PressureEnum', null, global);
goog.exportSymbol('proto.bosdyn.api.TemperatureEnum', null, global);
goog.exportSymbol('proto.bosdyn.api.Units', null, global);
goog.exportSymbol('proto.bosdyn.api.Units.UnitsCase', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bosdyn.api.Units = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.bosdyn.api.Units.oneofGroups_);
};
goog.inherits(proto.bosdyn.api.Units, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bosdyn.api.Units.displayName = 'proto.bosdyn.api.Units';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.bosdyn.api.Units.oneofGroups_ = [[1,2,3]];

/**
 * @enum {number}
 */
proto.bosdyn.api.Units.UnitsCase = {
  UNITS_NOT_SET: 0,
  NAME: 1,
  TEMP: 2,
  PRESS: 3
};

/**
 * @return {proto.bosdyn.api.Units.UnitsCase}
 */
proto.bosdyn.api.Units.prototype.getUnitsCase = function() {
  return /** @type {proto.bosdyn.api.Units.UnitsCase} */(jspb.Message.computeOneofCase(this, proto.bosdyn.api.Units.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bosdyn.api.Units.prototype.toObject = function(opt_includeInstance) {
  return proto.bosdyn.api.Units.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bosdyn.api.Units} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bosdyn.api.Units.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    temp: jspb.Message.getFieldWithDefault(msg, 2, 0),
    press: jspb.Message.getFieldWithDefault(msg, 3, 0),
    isRelative: jspb.Message.getBooleanFieldWithDefault(msg, 4, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bosdyn.api.Units}
 */
proto.bosdyn.api.Units.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bosdyn.api.Units;
  return proto.bosdyn.api.Units.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bosdyn.api.Units} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bosdyn.api.Units}
 */
proto.bosdyn.api.Units.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {!proto.bosdyn.api.TemperatureEnum} */ (reader.readEnum());
      msg.setTemp(value);
      break;
    case 3:
      var value = /** @type {!proto.bosdyn.api.PressureEnum} */ (reader.readEnum());
      msg.setPress(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsRelative(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bosdyn.api.Units.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bosdyn.api.Units.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bosdyn.api.Units} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bosdyn.api.Units.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {!proto.bosdyn.api.TemperatureEnum} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = /** @type {!proto.bosdyn.api.PressureEnum} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getIsRelative();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.bosdyn.api.Units.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.bosdyn.api.Units} returns this
 */
proto.bosdyn.api.Units.prototype.setName = function(value) {
  return jspb.Message.setOneofField(this, 1, proto.bosdyn.api.Units.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.bosdyn.api.Units} returns this
 */
proto.bosdyn.api.Units.prototype.clearName = function() {
  return jspb.Message.setOneofField(this, 1, proto.bosdyn.api.Units.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bosdyn.api.Units.prototype.hasName = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional TemperatureEnum temp = 2;
 * @return {!proto.bosdyn.api.TemperatureEnum}
 */
proto.bosdyn.api.Units.prototype.getTemp = function() {
  return /** @type {!proto.bosdyn.api.TemperatureEnum} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.bosdyn.api.TemperatureEnum} value
 * @return {!proto.bosdyn.api.Units} returns this
 */
proto.bosdyn.api.Units.prototype.setTemp = function(value) {
  return jspb.Message.setOneofField(this, 2, proto.bosdyn.api.Units.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.bosdyn.api.Units} returns this
 */
proto.bosdyn.api.Units.prototype.clearTemp = function() {
  return jspb.Message.setOneofField(this, 2, proto.bosdyn.api.Units.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bosdyn.api.Units.prototype.hasTemp = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional PressureEnum press = 3;
 * @return {!proto.bosdyn.api.PressureEnum}
 */
proto.bosdyn.api.Units.prototype.getPress = function() {
  return /** @type {!proto.bosdyn.api.PressureEnum} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.bosdyn.api.PressureEnum} value
 * @return {!proto.bosdyn.api.Units} returns this
 */
proto.bosdyn.api.Units.prototype.setPress = function(value) {
  return jspb.Message.setOneofField(this, 3, proto.bosdyn.api.Units.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.bosdyn.api.Units} returns this
 */
proto.bosdyn.api.Units.prototype.clearPress = function() {
  return jspb.Message.setOneofField(this, 3, proto.bosdyn.api.Units.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bosdyn.api.Units.prototype.hasPress = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional bool is_relative = 4;
 * @return {boolean}
 */
proto.bosdyn.api.Units.prototype.getIsRelative = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.bosdyn.api.Units} returns this
 */
proto.bosdyn.api.Units.prototype.setIsRelative = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * @enum {number}
 */
proto.bosdyn.api.TemperatureEnum = {
  TEMPERATURE_UNKNOWN: 0,
  TEMPERATURE_KELVIN: 1,
  TEMPERATURE_CELSIUS: 2,
  TEMPERATURE_FAHRENHEIT: 3
};

/**
 * @enum {number}
 */
proto.bosdyn.api.PressureEnum = {
  PRESSURE_UNKNOWN: 0,
  PRESSURE_PSI: 1,
  PRESSURE_KPA: 2,
  PRESSURE_BAR: 3
};

goog.object.extend(exports, proto.bosdyn.api);
