/**
 * @file The entry point of the package, require('spot-sdk-js'): the public API of the SDK. The clients of the Spot CAM,
 * of the GPS and of Orbit, and the modules of generic names (text and JSON formats of the messages, images, protobuf
 * descriptors) are in the namespaces spotCam, gps, orbit, textFormat, jsonFormat, imageUtil and descriptorPool. A few
 * names are exported by several modules with different values (e.g. the NoTimeSyncError of graph_nav, robot_command
 * and audio_visual): they are required from their module, e.g. require('spot-sdk-js/src/bosdyn-client/graph_nav').
 */

'use strict';

// Symbol.dispose and Symbol.asyncDispose for the versions of Node without them, before the classes that use them.
Symbol.dispose ??= Symbol('Symbol.dispose');
Symbol.asyncDispose ??= Symbol('Symbol.asyncDispose');

const alertsPb = require('./bosdyn/api/alerts_pb');
const authPb = require('./bosdyn/api/auth_pb');
const {
  Animation,
  AnimationFileFormatError,
  COMMENT_DELIMITERS,
  GROUPED_HEADERS,
  OPTIONS_KEYWORDS_TO_FUNCTION,
  SINGLE_HEADERS,
  convertAnimationFileToProto,
  handleNestedDoubleValueParams,
  readAndFindAnimationParams,
  readAnimationParams,
  setProto,
  writeAnimationToDest,
} = require('./bosdyn-choreography-client/animation_file_to_proto');
const {
  ChoreographyClient,
  AnimationUploadHelper,
  InvalidUploadedChoreographyError,
  RobotCommandIssuesError,
  LeaseError,
  AnimationValidationFailedError,
  AnimationRejectedDanceActiveError,
  NoRecordedInformation,
  UnknownRecordingSessionId,
  RecordingBufferFull,
  IncompleteData,
  loadChoreographySequenceFromBinaryFile,
  loadChoreographySequenceFromTxtFile,
  saveChoreographySequenceToFile,
} = require('./bosdyn-choreography-client/choreography');
const {
  API_TIMEOUT_DEFAULT,
  fileToJson,
  doorAction,
  getValueByPath,
  makeAccessControlSystemApiCall,
  safeSubstitute,
} = require('./bosdyn-client/access_controlled_door_util');
const {
  AreaCallbackClient,
  AreaCallbackResponseError,
  InvalidCommandIdError,
  InvalidConfigError,
  ExpiredEndTimeError,
  MissingLeaseResourcesError,
  ShutdownCallbackFailedError,
} = require('./bosdyn-client/area_callback');
const {
  PathBlocked,
  IncorrectUsage,
  HandlerError,
  CallbackEnded,
  CallbackTimedOutError,
  RouteChangedResult,
  AreaCallbackRegionHandlerBase,
} = require('./bosdyn-client/area_callback_region_handler_base');
const { runService } = require('./bosdyn-client/area_callback_service_runner');
const { AreaCallbackServiceServicer } = require('./bosdyn-client/area_callback_service_servicer');
const { AreaCallbackServiceConfig, handleServiceFaults } = require('./bosdyn-client/area_callback_service_utils');
const { ArmSurfaceContactClient } = require('./bosdyn-client/arm_surface_contact');
const { AsyncTasks, AsyncGRPCTask, AsyncPeriodicGRPCTask, AsyncPeriodicQuery } = require('./bosdyn-client/async_tasks');
const {
  AudioVisualClient,
  AudioVisualResponseError,
  DoesNotExistError,
  PermanentBehaviorError,
  BehaviorExpiredError,
  InvalidBehaviorError,
  InvalidClientError,
  checkColor,
  clampAndNormalizeColor,
} = require('./bosdyn-client/audio_visual');
const { AudioVisualHelper } = require('./bosdyn-client/audio_visual_helper');
const {
  AuthClient,
  AuthResponseError,
  InvalidLoginError,
  InvalidTokenError,
  TemporarilyLockedOutError,
} = require('./bosdyn-client/auth');
const { AutoReturnClient, AutoReturnResponseError, InvalidParameterError } = require('./bosdyn-client/auto_return');
const {
  AutowalkClient,
  AutowalkResponseError,
  CompilationError,
  ValidationError,
} = require('./bosdyn-client/autowalk');
const { DEFAULT_OUTPUT, downloadData } = require('./bosdyn-client/bddf_download');
const {
  DEFAULT_MAX_MESSAGE_LENGTH,
  DEFAULT_KEEP_ALIVE_TIME_MS,
  DEFAULT_HEADER_BUFFER_LENGTH,
  refreshingAccessTokenAuthMetadataPlugin,
  createSecureChannelCreds,
  createSecureChannel,
  createInsecureChannel,
  generateChannelOptions,
  translateException,
} = require('./bosdyn-client/channel');
const {
  DEFAULT_RPC_TIMEOUT,
  RPC_METHOD,
  BaseClient,
  commonHeaderErrors,
  streamingCommonHeaderErrors,
  commonLeaseErrors,
  streamingCommonLeaseErrors,
  customParamsError,
  errorFactory,
  commonLicenseErrors,
  handleUnsetStatusError,
  handleCommonHeaderErrors,
  handleLeaseUseResultErrors,
  handleCustomParamsErrors,
  handleLicenseErrors,
  handleLicenseErrorsIfPresent,
  getSelfIp,
} = require('./bosdyn-client/common');
const {
  DataAcquisitionClient,
  DataAcquisitionResponseError,
  UnknownCaptureTypeError,
  CancellationFailedError,
  metadataToProto,
  acquireDataError,
} = require('./bosdyn-client/data_acquisition');
const {
  issueAcquireDataRequest,
  acquireAndProcessRequest,
  cancelAcquisitionRequest,
  cleanFilename,
  makeTimeQueryParams,
  makeTimeQueryParamsFromGroupName,
  downloadDataREST,
} = require('./bosdyn-client/data_acquisition_helpers');
const { DataAcquisitionPluginClient } = require('./bosdyn-client/data_acquisition_plugin');
const {
  kDefaultRequestExpiration,
  RequestCancelledError,
  makeError,
  RequestState,
  DataAcquisitionStoreHelper,
  DataAcquisitionPluginService,
  RequestManager,
} = require('./bosdyn-client/data_acquisition_plugin_service');
const { DataAcquisitionStoreClient } = require('./bosdyn-client/data_acquisition_store');
const {
  DataBufferClient,
  LoggingHandler,
  isNotRpc,
  isNotTextLog,
  logEvent,
  makeParameter,
} = require('./bosdyn-client/data_buffer');
const {
  splitSerialized,
  chunkSerialized,
  chunkMessage,
  parseFromChunks,
  serializedFromChunks,
  serializedFromMessages,
  serializedFromStrings,
} = require('./bosdyn-client/data_chunk');
const { DataServiceClient } = require('./bosdyn-client/data_service');
const { DirectoryResponseError, NonexistentServiceError, DirectoryClient } = require('./bosdyn-client/directory');
const {
  DirectoryRegistrationResponseError,
  ServiceAlreadyExistsError,
  ServiceDoesNotExistError,
  DirectoryRegistrationClient,
  DirectoryRegistrationKeepAlive,
  resetServiceRegistration,
} = require('./bosdyn-client/directory_registration');
const {
  DockingClient,
  blockingDockRobot,
  blockingGoToPrepPose,
  blockingUndock,
  getDockId,
} = require('./bosdyn-client/docking');
const { DoorClient } = require('./bosdyn-client/door');
const { ErrorCallbackResult } = require('./bosdyn-client/error_callback_result');
const {
  StopLevel,
  EstopResponseError,
  EndpointUnknownError,
  IncorrectChallengeResponseError,
  EndpointMismatchError,
  ConfigMismatchError,
  InvalidEndpointError,
  InvalidIdError,
  MotorsOnError,
  EstopClient,
  EstopEndpoint,
  EstopKeepAlive,
  isEstopped,
  responseFromChallenge,
} = require('./bosdyn-client/estop');
const {
  BosdynError,
  ValueError,
  ResponseError,
  InvalidRequestError,
  LeaseUseError,
  LicenseError,
  ServerError,
  InternalServerError,
  UnsetStatusError,
  RpcError,
  RetryableRpcError,
  PersistentRpcError,
  ClientCancelledOperationError,
  InvalidClientCertificateError,
  NonexistentAuthorityError,
  PermissionDeniedError,
  ProxyConnectionError,
  ResponseTooLargeError,
  ServiceUnavailableError,
  TooManyRequestsError,
  ServiceFailedDuringExecutionError,
  TimedOutError,
  UnableToConnectToRobotError,
  RetryableUnavailableError,
  ConnectionResetError,
  UnauthenticatedError,
  UnknownDnsNameError,
  NotFoundError,
  UnimplementedError,
  TransientFailureError,
  InternalDeserializationError,
  TimeSyncRequired,
  CustomParamError,
} = require('./bosdyn-client/exceptions');
const {
  FaultClient,
  FaultResponseError,
  ServiceFaultAlreadyExistsError,
  ServiceFaultDoesNotExistError,
} = require('./bosdyn-client/fault');
const {
  ValidateFrameTreeError,
  ValidateFrameTreeUnknownFrameError,
  ValidateFrameTreeCycleError,
  ValidateFrameTreeDisjointError,
  validateFrameTreeSnapshot,
  getATformB,
  getSe2ATformB,
  expressSe2VelocityInNewFrame,
  expressSe3VelocityInNewFrame,
  getOdomTformBody,
  getVisionTformBody,
  GenerateTreeError,
  ChildFrameInTree,
  addEdgeToTree,
  getFrameNames,
  isGravityAlignedFrameName,
  VISION_FRAME_NAME,
  BODY_FRAME_NAME,
  GRAV_ALIGNED_BODY_FRAME_NAME,
  ODOM_FRAME_NAME,
  SEED_FRAME_NAME,
  GROUND_PLANE_FRAME_NAME,
  HAND_FRAME_NAME,
  UNKNOWN_FRAME_NAME,
  RAYCAST_FRAME_NAME,
  TOOL_FRAME_NAME,
  DESIRED_TOOL_FRAME_NAME,
  TASK_FRAME_NAME,
  DESIRED_TOOL_AT_END_FRAME_NAME,
  MEASURED_TOOL_AT_START_FRAME_NAME,
  GAZE_TARGET_FRAME_NAME,
  FRONT_LEFT_FOOT_FRAME_NAME,
  FRONT_RIGHT_FOOT_FRAME_NAME,
  HIND_LEFT_FOOT_FRAME_NAME,
  HIND_RIGHT_FOOT_FRAME_NAME,
  FOOT_FRAME_NAMES,
  WR1_FRAME_NAME,
  WAYPOINT_FRAME_NAME,
} = require('./bosdyn-client/frame_helpers');
const gps = require('./bosdyn-client/gps');
const {
  GraphNavClient,
  GraphNavServiceResponseError,
  UploadWaypointSnapshotError,
  UploadGraphError,
  IncompatibleSensorsError,
  AreaCallbackMapError,
  CannotModifyMapDuringRecordingError,
  NoAnchoringError,
  InvalidPoseError,
  InvalidGPSError,
  UnrecognizedCommandError,
  RequestAbortedError,
  RequestFailedError,
  RobotFaultedError,
  UnknownMapInformationError,
  TimeError,
  CommandExpiredError,
  RobotStateError,
  IsRecordingError,
  RouteError,
  ConstraintFaultError,
  InvalidEdgeError,
  UnkownRouteElementsError,
  UnknownRouteElementsError,
  NoPathError,
  RouteNavigationError,
  FeatureDesertError,
  RouteNotUpdatingError,
  RobotLostError,
  RobotNotLocalizedToRouteError,
  RobotStuckError,
  UnrecongizedCommandError,
} = require('./bosdyn-client/graph_nav');
const { downloadToDisk } = require('./bosdyn-client/graph_nav_download');
const { uploadFromDisk } = require('./bosdyn-client/graph_nav_upload');
const { GripperCameraParamClient } = require('./bosdyn-client/gripper_camera_param');
const { HazardAvoidanceClient, AddHazardsResponseError } = require('./bosdyn-client/hazard_avoidance');
const {
  ImageClient,
  ImageResponseError,
  UnknownImageSourceError,
  ImageDataError,
  buildImageRequest,
  writePgmOrPpm,
  writeImageData,
  saveImagesAsFiles,
  pixelToCameraSpace,
  depthImageToPointcloud,
  MAX_DEPTH_IMAGE_RANGE,
  UnsupportedImageFormatRequestedError,
  UnsupportedPixelFormatRequestedError,
  UnsupportedResizeRatioRequestedError,
} = require('./bosdyn-client/image');
const {
  CLEAR_FAULT_RPC_TIMEOUT_MSECS,
  convertRgbToGrayscale,
  CaptureLock,
  CameraInterface,
  VisualImageSource,
  ThreadCaptureOutput,
  ImageCaptureThread,
  CameraBaseImageServicer,
} = require('./bosdyn-client/image_service_helpers');
const { InverseKinematicsClient } = require('./bosdyn-client/inverse_kinematics');
const { IREnableDisableServiceClient } = require('./bosdyn-client/ir_enable_disable');
const {
  Policy,
  KeepaliveClient,
  PolicyKeepalive,
  removeAllPolicies,
  KeepaliveResponseError,
  InvalidPolicyError,
} = require('./bosdyn-client/keepalive');
const {
  InvalidLeaseError,
  LeaseResponseError,
  DisplacedLeaseError,
  InvalidResourceError,
  NotAuthoritativeServiceError,
  ResourceAlreadyClaimedError,
  RevokedLeaseError,
  UnmanagedResourceError,
  WrongEpochError,
  NotActiveLeaseError,
  NoSuchLease,
  LeaseNotOwnedByWallet,
  Lease,
  LeaseState,
  LeaseWallet,
  LeaseClient,
  LeaseWalletRequestProcessor,
  LeaseWalletResponseProcessor,
  addLeaseWalletProcessors,
  LeaseKeepAlive,
  testActiveLease,
  DEFAULT_RESOURCES,
} = require('./bosdyn-client/lease');
const { ResourceHierarchy } = require('./bosdyn-client/lease_resource_hierarchy');
const { LeaseValidator, LeaseValidatorResponseProcessor } = require('./bosdyn-client/lease_validator');
const { LicenseClient } = require('./bosdyn-client/license');
const { LocalGridClient } = require('./bosdyn-client/local_grid');
const {
  LogStatusClient,
  LogStatusResponseError,
  ExperimentAlreadyRunningError,
  InactiveLogError,
  ConcurrencyLimitReachedError,
  NoDataForEventError,
} = require('./bosdyn-client/log_status');
const { LoggerUtil } = require('./bosdyn-client/logger_util');
const { ManipulationApiClient } = require('./bosdyn-client/manipulation_api_client');
const {
  MapProcessingServiceClient,
  MapProcessingServiceResponseError,
  MissingSnapshotsError,
  OptimizationFailureError,
  InvalidParamsError,
  MaxIterationsError,
  MaxTimeError,
  InvalidHintsError,
  InvalidGravityAlignmentError,
  ConstraintViolationError,
  MapModifiedError,
} = require('./bosdyn-client/map_processing');
const {
  Vec2,
  Vec3,
  SE2Pose,
  SE2Velocity,
  SE3Velocity,
  SE3Pose,
  Quat,
  poseToXyzYaw,
  isWithinThreshold,
  recenterAngle,
  angleDiff,
  angleDiffDegrees,
  radiansToDegrees,
  skewMatrix3d,
  skewMatrix2d,
  matrixFromProto,
  transformSe2velocity,
  transformSe3velocity,
  quatToEulerZYX,
  recenterValueMod,
  recenterAngleMod,
} = require('./bosdyn-client/math_helpers');
const { MetricsLoggingClient, MissingKeysError, UnableToOptOutError } = require('./bosdyn-client/metrics_logging');
const {
  ExternalServiceNotFoundError,
  ExternalServerError,
  NetworkComputeRotationError,
  NetworkComputeAnalysisFailedError,
  NetworkComputeBridgeClient,
} = require('./bosdyn-client/network_compute_bridge_client');
const { PayloadClient } = require('./bosdyn-client/payload');
const {
  PayloadRegistrationResponseError,
  InvalidPayloadCredentialsError,
  PayloadNotAuthorizedError,
  PayloadAlreadyExistsError,
  PayloadDoesNotExistError,
  PayloadRegistrationClient,
  PayloadRegistrationKeepAlive,
} = require('./bosdyn-client/payload_registration');
const { PayloadSoftwareUpdate, PayloadSoftwareUpdateClient } = require('./bosdyn-client/payload_software_update');
const {
  PayloadSoftwareUpdateInitiation,
  PayloadSoftwareUpdateInitiationClient,
} = require('./bosdyn-client/payload_software_update_initiation');
const {
  PointCloudClient,
  buildPcRequest,
  PointCloudResponseError,
  UnknownPointCloudSourceError,
  PointCloudDataError,
  PointCloudTypeError,
} = require('./bosdyn-client/point_cloud');
const {
  PowerResponseError,
  ShorePowerConnectedError,
  BatteryMissingError,
  CommandInProgressError,
  EstoppedError,
  OverriddenError,
  KeepaliveMotorsOffError,
  FaultedError,
  FanControlTemperatureError,
  SafetyStopIncompatibleHardwareError,
  SafetyStopFailedError,
  SafetyStopUnknownStopTypeError,
  PowerError,
  PowerClient,
  powerOn,
  powerOff,
  powerOnMotors,
  powerOffMotors,
  safePowerOffRobot,
  safePowerOffMotors,
  powerOffRobot,
  safePowerCycleRobot,
  powerCycleRobot,
  safeSoftRebootRobot,
  softRebootRobot,
  powerOffPayloadPorts,
  powerOnPayloadPorts,
  powerOffWifiRadio,
  powerOnWifiRadio,
  isPoweredOn,
} = require('./bosdyn-client/power');
const { AddRequestHeader, DataBufferLoggingProcessor, logAllRpcs } = require('./bosdyn-client/processors');
const { RayCastClient, RayCastResponseError, InvalidIntersectionTypeError } = require('./bosdyn-client/ray_cast');
const {
  WaypointRegion,
  GraphNavRecordingServiceClient,
  RecordingServiceResponseError,
  CouldNotCreateWaypointError,
  NotRecordingError,
  EdgeExistsError,
  EdgeMissingTransformError,
  NotLocalizedToEndError,
  FollowingRouteError,
  NotLocalizedToExistingMapError,
  TooFarFromExistingMapError,
  RemoteCloudFailureNotInDirectoryError,
  RemoteCloudFailureNoDataError,
  NotReadyYetError,
  MissingFiducialsError,
  FiducialPoseError,
} = require('./bosdyn-client/recording');
const {
  RobotError,
  UnregisteredServiceError,
  UnregisteredServiceNameError,
  UnregisteredServiceTypeError,
  Robot,
} = require('./bosdyn-client/robot');
const {
  EDIT_TREE_CONVERT_LOCAL_TIME_TO_ROBOT_TIME,
  END_TIME_EDIT_TREE,
  RobotCommandResponseError,
  ExpiredError,
  NotPoweredOnError,
  BehaviorFaultError,
  DockedError,
  NotClearedError,
  UnsupportedError,
  CommandFailedError,
  CommandFailedErrorWithFeedback,
  RobotCommandClient,
  RobotCommandBuilder,
  RobotCommandStreamingClient,
  blockingCommand,
  blockingStand,
  blockingSit,
  blockingSelfright,
  blockUntilArmArrives,
  blockForTrajectoryCmd,
} = require('./bosdyn-client/robot_command');
const { RobotIdClient, compareVersions, toVersionArray, versionTuple } = require('./bosdyn-client/robot_id');
const { RobotStateClient, RobotStateStreamingClient, hasArm } = require('./bosdyn-client/robot_state');
const {
  generateClientName,
  createStandardSdk,
  BOSDYN_RESOURCE_ROOT,
  BOSDYN_CA_CERT_ENV,
  Sdk,
  SdkError,
  UnsetAppTokenError,
  UnableToLoadAppTokenError,
} = require('./bosdyn-client/sdk');
const {
  GrpcServiceRunner,
  ResponseContext,
  populateResponseHeader,
  stripLargeBytesFields,
  getBytesFieldAllowlist,
  stripImageResponse,
  stripGetImageResponse,
  stripLocalGridResponses,
  stripStoreImageRequest,
  stripStoreDataRequest,
  stripRecordSignalTick,
  stripRecordDataBlob,
} = require('./bosdyn-client/server_util');
const {
  InvalidCustomParamSpecError,
  InvalidCustomParamValueError,
  checkTypesMatch,
  validateDictSpec,
  createValueValidator,
  dictParamsToDict,
  listParamsToList,
  oneofParamToDict,
  customSpecToDefault,
  dictSpecToDefault,
  listSpecToDefault,
  intSpecToDefault,
  doubleSpecToDefault,
  stringSpecToDefault,
  roiSpecToDefault,
  boolSpecToDefault,
  oneOfSpecToDefault,
  dictParamCoerceTo,
  listParamCoerceTo,
  intParamCoerceTo,
  doubleParamCoerceTo,
  stringParamCoerceTo,
  roiParamCoerceTo,
  oneOfParamCoerceTo,
  customParamCoerceTo,
  makeCustomParamSpec,
  makeDictChildSpec,
  makeDictParamSpec,
  makeOneOfChildSpec,
  makeOneOfParamSpec,
  makeListParamSpec,
  makeInt64ParamSpec,
  makeDoubleParamSpec,
  makeStringParamSpec,
  makeBoolParamSpec,
  makeRegionOfInterestParamSpec,
  makeUserInterfaceInfo,
  makeRoiServiceAndSource,
} = require('./bosdyn-client/service_customization_helpers');
const {
  buildMaxAlertSpec,
  buildSimpleSignal,
  buildCapabilityLiveData,
  buildLiveDataResponse,
  getData,
} = require('./bosdyn-client/signals_helpers');
const spotCam = require('./bosdyn-client/spot_cam');
const {
  SpotCheckError,
  SpotCheckResponseError,
  SpotCheckUnexpectedPowerChangeError,
  SpotCheckImuCheckError,
  SpotCheckNotSittingError,
  SpotCheckLoadcellTimeoutError,
  SpotCheckPowerOnFailure,
  SpotCheckEndstopTimeoutError,
  SpotCheckStandFailureError,
  SpotCheckCameraTimeoutError,
  SpotCheckGroundCheckError,
  SpotCheckTimedOutError,
  CameraSpotCheckTimedOutError,
  CameraSpotCheckFeedbackError,
  CameraCalibrationResponseError,
  CameraCalibrationUserCanceledError,
  CameraCalibrationPowerError,
  CameraCalibrationTargetNotCenteredError,
  CameraCalibrationRobotCommandError,
  CameraCalibrationCalibrationError,
  CameraCalibrationInternalError,
  CameraCalibrationTimedOutError,
  SpotCheckClient,
  runSpotCheck,
  runCameraCalibration,
} = require('./bosdyn-client/spot_check');
const {
  TimeSyncError,
  NotEstablishedError,
  InactiveThreadError,
  TimeSyncClient,
  TimeSyncEndpoint,
  TimeSyncThread,
  timespecToRobotTimespan,
  robotTimeRangeFromDatetimes,
  robotTimeRangeFromNanoseconds,
  updateTimeFilter,
  updateTimestampFilter,
} = require('./bosdyn-client/time_sync');
const {
  TokenCache,
  TokenCacheFilesystem,
  TokenCacheError,
  ClearFailedError,
  NotInCacheError,
  WriteFailedError,
} = require('./bosdyn-client/token_cache');
const {
  TokenManager,
  USER_TOKEN_REFRESH_TIME_DELTA,
  USER_TOKEN_RETRY_INTERVAL_START,
} = require('./bosdyn-client/token_manager');
const { TEMPERATURES_NAMES, PRESSURE_NAMES, unitsToString } = require('./bosdyn-client/units_helpers');
const {
  MAX_REDIRECTS,
  InterfaceNameNotFound,
  RequestError,
  Response,
  safeApiCall,
  validateUrl,
} = require('./bosdyn-client/url_validation_util');
const {
  checkOptions,
  cliLoginPrompt,
  cliAuth,
  authenticate,
  setupLogging,
  DedupLoggingMessages,
  doesDedupFilterExist,
  safePbEnumToString,
  getLogger,
  addCommonArguments,
  addCredentialsArguments,
  addBaseArguments,
  addPayloadCredentialsArguments,
  addPayloadCredentialsFileArgument,
  addServiceHostingArguments,
  addServiceEndpointArguments,
  readPayloadCredentials,
  readOrCreatePayloadCredentials,
  getGuidAndSecret,
  DefaultDict,
  polyfillDispose,
  buildProtoIndex,
  getProtoTypeName,
  protoTypeName,
  httpsGetUnverified,
} = require('./bosdyn-client/util');
const {
  WorldObjectClient,
  makeAddWorldObjectReq,
  makeDeleteWorldObjectReq,
  makeChangeWorldObjectReq,
  sendAddMutationRequests,
  sendDeleteMutationRequests,
} = require('./bosdyn-client/world_object');
const { BaseDataReader } = require('./bosdyn-core/bddf/base_data_reader');
const { BlockWriter } = require('./bosdyn-core/bddf/block_writer');
const { MessageChannel, TypedMessageChannel, GrpcRequests, GrpcResponses } = require('./bosdyn-core/bddf/bosdyn');
const {
  MAGIC,
  END_MAGIC,
  BLOCK_HEADER_SIZE_MASK,
  BLOCK_HEADER_TYPE_MASK,
  DATA_BLOCK_TYPE,
  DESCRIPTOR_BLOCK_TYPE,
  END_BLOCK_TYPE,
  PROTOBUF_CONTENT_TYPE,
  SHA1_DIGEST_NBYTES,
  INDEX_OFFSET_OFFSET,
  LOGGER,
  POD_TYPE_TO_STRUCT,
  POD_TYPE_TO_NUM_BYTES,
  DataError,
  AddSeriesError,
  SeriesNotUniqueError,
  ChecksumError,
  DataFormatError,
  EOFError,
  SeriesIdentifier,
  packPodValues,
  unpackPodValues,
} = require('./bosdyn-core/bddf/common');
const { DataReader } = require('./bosdyn-core/bddf/data_reader');
const { DataWriter } = require('./bosdyn-core/bddf/data_writer');
const { FileIndexer } = require('./bosdyn-core/bddf/file_indexer');
const { GrpcProtoReader } = require('./bosdyn-core/bddf/grpc_proto_reader');
const { GrpcReader } = require('./bosdyn-core/bddf/grpc_reader');
const { GrpcServiceReader } = require('./bosdyn-core/bddf/grpc_service_reader');
const { GrpcServiceWriter } = require('./bosdyn-core/bddf/grpc_service_writer');
const { MessageReader } = require('./bosdyn-core/bddf/message_reader');
const { PodSeriesReader } = require('./bosdyn-core/bddf/pod_series_reader');
const { PodSeriesWriter } = require('./bosdyn-core/bddf/pod_series_writer');
const { ProtobufChannelReader } = require('./bosdyn-core/bddf/protobuf_channel_reader');
const { ProtobufReader } = require('./bosdyn-core/bddf/protobuf_reader');
const { ProtobufSeriesWriter } = require('./bosdyn-core/bddf/protobuf_series_writer');
const { StreamDataReader } = require('./bosdyn-core/bddf/stream_data_reader');
const descriptorPool = require('./bosdyn-core/descriptor_pool');
const { Event } = require('./bosdyn-core/event');
const { EulerZXY } = require('./bosdyn-core/geometry');
const imageUtil = require('./bosdyn-core/image_util');
const jsonFormat = require('./bosdyn-core/json_format');
const { Lock } = require('./bosdyn-core/lock');
const { Queue, QueueFullError } = require('./bosdyn-core/queue');
const textFormat = require('./bosdyn-core/text_format');
const {
  TIME_FORMAT_DESC,
  RobotTimeConverter,
  distanceStr,
  formatFixed,
  formatMetric,
  setProcessName,
  secsToHms,
  timestampToDatetime,
  timestampToNsec,
  timestampToNsecBigInt,
  timestampToSec,
  toInt64String,
  toUint64String,
  getNanoSecTime,
  nsecToTimestamp,
  nowTimestamp,
  setTimestampFromDatetime,
  setTimestampFromNsec,
  setTimestampFromNow,
  setClockSource,
  systemTimeSec,
  nowNsec,
  nowMsec,
  nowSec,
  secToNsec,
  nsecToSec,
  secToMsec,
  msecToSec,
  timestampStr,
  durationToSeconds,
  durationStr,
  sum,
  accumulate,
  slice,
  secondsToDuration,
  secondsToTimestamp,
  parseTimespan,
  parseDatetime,
  DatetimeParseError,
} = require('./bosdyn-core/util');
const {
  MissionClient,
  MissionResponseError,
  InvalidQuestionId,
  InvalidAnswerCode,
  QuestionAlreadyAnswered,
  CustomParamsError,
  IncompatibleAnswer,
  NoMissionError,
  NoMissionPlayingError,
} = require('./bosdyn-mission/client');
const { Result } = require('./bosdyn-mission/constants');
const {
  CompileError,
  UnknownType,
  MissingParameterError,
  InaccessibleParameterError,
  MessageOverrideError,
  NodeUnreferenceableError,
} = require('./bosdyn-mission/exceptions');
const {
  RemoteClient,
  InvalidSessionId,
  MissingInputs,
  MissingLeases,
  treeStatusFromTickStatus,
} = require('./bosdyn-mission/remote_client');
const {
  DUMMY_MESSAGE,
  InvalidConversion,
  treeToString,
  typeToFieldName,
  protoFromObject,
  jsVarToValue,
  jsTypeToPbType,
  jsTypeToVariableDeclInfo,
  jsVarToVariableDecl,
  severityToLogLevel,
  isStringIdentifier,
  fieldDescToPbType,
  safePbTypeToString,
  oneLineStr,
  nodeSpecToShortString,
  ResultFromProto,
  protoEnumToResultConstant,
  resultConstantToProtoEnum,
  mostRestrictiveTravelParams,
  getValueFromConstantValueMessage,
  getValueFromValueMessage,
  createValue,
  defineBlackboard,
  setBlackboard,
} = require('./bosdyn-mission/util');

const orbit = require('./bosdyn-orbit');

module.exports = {
  Animation,
  AnimationFileFormatError,
  COMMENT_DELIMITERS,
  GROUPED_HEADERS,
  OPTIONS_KEYWORDS_TO_FUNCTION,
  SINGLE_HEADERS,
  convertAnimationFileToProto,
  handleNestedDoubleValueParams,
  readAndFindAnimationParams,
  readAnimationParams,
  setProto,
  writeAnimationToDest,
  ChoreographyClient,
  AnimationUploadHelper,
  InvalidUploadedChoreographyError,
  RobotCommandIssuesError,
  LeaseError,
  AnimationValidationFailedError,
  AnimationRejectedDanceActiveError,
  NoRecordedInformation,
  UnknownRecordingSessionId,
  RecordingBufferFull,
  IncompleteData,
  loadChoreographySequenceFromBinaryFile,
  loadChoreographySequenceFromTxtFile,
  saveChoreographySequenceToFile,
  API_TIMEOUT_DEFAULT,
  fileToJson,
  doorAction,
  getValueByPath,
  makeAccessControlSystemApiCall,
  safeSubstitute,
  AreaCallbackClient,
  AreaCallbackResponseError,
  InvalidCommandIdError,
  InvalidConfigError,
  ExpiredEndTimeError,
  MissingLeaseResourcesError,
  ShutdownCallbackFailedError,
  PathBlocked,
  IncorrectUsage,
  HandlerError,
  CallbackEnded,
  CallbackTimedOutError,
  RouteChangedResult,
  AreaCallbackRegionHandlerBase,
  runService,
  AreaCallbackServiceServicer,
  AreaCallbackServiceConfig,
  handleServiceFaults,
  ArmSurfaceContactClient,
  AsyncTasks,
  AsyncGRPCTask,
  AsyncPeriodicGRPCTask,
  AsyncPeriodicQuery,
  AudioVisualClient,
  AudioVisualResponseError,
  DoesNotExistError,
  PermanentBehaviorError,
  BehaviorExpiredError,
  InvalidBehaviorError,
  InvalidClientError,
  checkColor,
  clampAndNormalizeColor,
  AudioVisualHelper,
  AuthClient,
  AuthResponseError,
  InvalidLoginError,
  InvalidTokenError,
  TemporarilyLockedOutError,
  AutoReturnClient,
  AutoReturnResponseError,
  InvalidParameterError,
  AutowalkClient,
  AutowalkResponseError,
  CompilationError,
  ValidationError,
  DEFAULT_OUTPUT,
  downloadData,
  DEFAULT_MAX_MESSAGE_LENGTH,
  DEFAULT_KEEP_ALIVE_TIME_MS,
  DEFAULT_HEADER_BUFFER_LENGTH,
  refreshingAccessTokenAuthMetadataPlugin,
  createSecureChannelCreds,
  createSecureChannel,
  createInsecureChannel,
  generateChannelOptions,
  translateException,
  DEFAULT_RPC_TIMEOUT,
  RPC_METHOD,
  BaseClient,
  commonHeaderErrors,
  streamingCommonHeaderErrors,
  commonLeaseErrors,
  streamingCommonLeaseErrors,
  customParamsError,
  errorFactory,
  commonLicenseErrors,
  handleUnsetStatusError,
  handleCommonHeaderErrors,
  handleLeaseUseResultErrors,
  handleCustomParamsErrors,
  handleLicenseErrors,
  handleLicenseErrorsIfPresent,
  getSelfIp,
  DataAcquisitionClient,
  DataAcquisitionResponseError,
  UnknownCaptureTypeError,
  CancellationFailedError,
  metadataToProto,
  acquireDataError,
  issueAcquireDataRequest,
  acquireAndProcessRequest,
  cancelAcquisitionRequest,
  cleanFilename,
  makeTimeQueryParams,
  makeTimeQueryParamsFromGroupName,
  downloadDataREST,
  DataAcquisitionPluginClient,
  kDefaultRequestExpiration,
  RequestCancelledError,
  makeError,
  RequestState,
  DataAcquisitionStoreHelper,
  DataAcquisitionPluginService,
  RequestManager,
  DataAcquisitionStoreClient,
  DataBufferClient,
  LoggingHandler,
  isNotRpc,
  isNotTextLog,
  logEvent,
  makeParameter,
  splitSerialized,
  chunkSerialized,
  chunkMessage,
  parseFromChunks,
  serializedFromChunks,
  serializedFromMessages,
  serializedFromStrings,
  DataServiceClient,
  DirectoryResponseError,
  NonexistentServiceError,
  DirectoryClient,
  DirectoryRegistrationResponseError,
  ServiceAlreadyExistsError,
  ServiceDoesNotExistError,
  DirectoryRegistrationClient,
  DirectoryRegistrationKeepAlive,
  resetServiceRegistration,
  DockingClient,
  blockingDockRobot,
  blockingGoToPrepPose,
  blockingUndock,
  getDockId,
  DoorClient,
  ErrorCallbackResult,
  StopLevel,
  EstopResponseError,
  EndpointUnknownError,
  IncorrectChallengeResponseError,
  EndpointMismatchError,
  ConfigMismatchError,
  InvalidEndpointError,
  InvalidIdError,
  MotorsOnError,
  EstopClient,
  EstopEndpoint,
  EstopKeepAlive,
  isEstopped,
  responseFromChallenge,
  BosdynError,
  ValueError,
  ResponseError,
  InvalidRequestError,
  LeaseUseError,
  LicenseError,
  ServerError,
  InternalServerError,
  UnsetStatusError,
  RpcError,
  RetryableRpcError,
  PersistentRpcError,
  ClientCancelledOperationError,
  InvalidClientCertificateError,
  NonexistentAuthorityError,
  PermissionDeniedError,
  ProxyConnectionError,
  ResponseTooLargeError,
  ServiceUnavailableError,
  TooManyRequestsError,
  ServiceFailedDuringExecutionError,
  TimedOutError,
  UnableToConnectToRobotError,
  RetryableUnavailableError,
  ConnectionResetError,
  UnauthenticatedError,
  UnknownDnsNameError,
  NotFoundError,
  UnimplementedError,
  TransientFailureError,
  InternalDeserializationError,
  TimeSyncRequired,
  CustomParamError,
  FaultClient,
  FaultResponseError,
  ServiceFaultAlreadyExistsError,
  ServiceFaultDoesNotExistError,
  ValidateFrameTreeError,
  ValidateFrameTreeUnknownFrameError,
  ValidateFrameTreeCycleError,
  ValidateFrameTreeDisjointError,
  validateFrameTreeSnapshot,
  getATformB,
  getSe2ATformB,
  expressSe2VelocityInNewFrame,
  expressSe3VelocityInNewFrame,
  getOdomTformBody,
  getVisionTformBody,
  GenerateTreeError,
  ChildFrameInTree,
  addEdgeToTree,
  getFrameNames,
  isGravityAlignedFrameName,
  VISION_FRAME_NAME,
  BODY_FRAME_NAME,
  GRAV_ALIGNED_BODY_FRAME_NAME,
  ODOM_FRAME_NAME,
  SEED_FRAME_NAME,
  GROUND_PLANE_FRAME_NAME,
  HAND_FRAME_NAME,
  UNKNOWN_FRAME_NAME,
  RAYCAST_FRAME_NAME,
  TOOL_FRAME_NAME,
  DESIRED_TOOL_FRAME_NAME,
  TASK_FRAME_NAME,
  DESIRED_TOOL_AT_END_FRAME_NAME,
  MEASURED_TOOL_AT_START_FRAME_NAME,
  GAZE_TARGET_FRAME_NAME,
  FRONT_LEFT_FOOT_FRAME_NAME,
  FRONT_RIGHT_FOOT_FRAME_NAME,
  HIND_LEFT_FOOT_FRAME_NAME,
  HIND_RIGHT_FOOT_FRAME_NAME,
  FOOT_FRAME_NAMES,
  WR1_FRAME_NAME,
  WAYPOINT_FRAME_NAME,
  GraphNavClient,
  GraphNavServiceResponseError,
  UploadWaypointSnapshotError,
  UploadGraphError,
  IncompatibleSensorsError,
  AreaCallbackMapError,
  CannotModifyMapDuringRecordingError,
  NoAnchoringError,
  InvalidPoseError,
  InvalidGPSError,
  UnrecognizedCommandError,
  RequestAbortedError,
  RequestFailedError,
  RobotFaultedError,
  UnknownMapInformationError,
  TimeError,
  CommandExpiredError,
  RobotStateError,
  IsRecordingError,
  RouteError,
  ConstraintFaultError,
  InvalidEdgeError,
  UnkownRouteElementsError,
  UnknownRouteElementsError,
  NoPathError,
  RouteNavigationError,
  FeatureDesertError,
  RouteNotUpdatingError,
  RobotLostError,
  RobotNotLocalizedToRouteError,
  RobotStuckError,
  UnrecongizedCommandError,
  downloadToDisk,
  uploadFromDisk,
  GripperCameraParamClient,
  HazardAvoidanceClient,
  AddHazardsResponseError,
  ImageClient,
  ImageResponseError,
  UnknownImageSourceError,
  ImageDataError,
  buildImageRequest,
  writePgmOrPpm,
  writeImageData,
  saveImagesAsFiles,
  pixelToCameraSpace,
  depthImageToPointcloud,
  MAX_DEPTH_IMAGE_RANGE,
  UnsupportedImageFormatRequestedError,
  UnsupportedPixelFormatRequestedError,
  UnsupportedResizeRatioRequestedError,
  CLEAR_FAULT_RPC_TIMEOUT_MSECS,
  convertRgbToGrayscale,
  CaptureLock,
  CameraInterface,
  VisualImageSource,
  ThreadCaptureOutput,
  ImageCaptureThread,
  CameraBaseImageServicer,
  InverseKinematicsClient,
  IREnableDisableServiceClient,
  Policy,
  KeepaliveClient,
  PolicyKeepalive,
  removeAllPolicies,
  KeepaliveResponseError,
  InvalidPolicyError,
  InvalidLeaseError,
  LeaseResponseError,
  DisplacedLeaseError,
  InvalidResourceError,
  NotAuthoritativeServiceError,
  ResourceAlreadyClaimedError,
  RevokedLeaseError,
  UnmanagedResourceError,
  WrongEpochError,
  NotActiveLeaseError,
  NoSuchLease,
  LeaseNotOwnedByWallet,
  Lease,
  LeaseState,
  LeaseWallet,
  LeaseClient,
  LeaseWalletRequestProcessor,
  LeaseWalletResponseProcessor,
  addLeaseWalletProcessors,
  LeaseKeepAlive,
  testActiveLease,
  DEFAULT_RESOURCES,
  ResourceHierarchy,
  LeaseValidator,
  LeaseValidatorResponseProcessor,
  LicenseClient,
  LocalGridClient,
  LogStatusClient,
  LogStatusResponseError,
  ExperimentAlreadyRunningError,
  InactiveLogError,
  ConcurrencyLimitReachedError,
  NoDataForEventError,
  LoggerUtil,
  ManipulationApiClient,
  MapProcessingServiceClient,
  MapProcessingServiceResponseError,
  MissingSnapshotsError,
  OptimizationFailureError,
  InvalidParamsError,
  MaxIterationsError,
  MaxTimeError,
  InvalidHintsError,
  InvalidGravityAlignmentError,
  ConstraintViolationError,
  MapModifiedError,
  Vec2,
  Vec3,
  SE2Pose,
  SE2Velocity,
  SE3Velocity,
  SE3Pose,
  Quat,
  poseToXyzYaw,
  isWithinThreshold,
  recenterAngle,
  angleDiff,
  angleDiffDegrees,
  radiansToDegrees,
  skewMatrix3d,
  skewMatrix2d,
  matrixFromProto,
  transformSe2velocity,
  transformSe3velocity,
  quatToEulerZYX,
  recenterValueMod,
  recenterAngleMod,
  MetricsLoggingClient,
  MissingKeysError,
  UnableToOptOutError,
  ExternalServiceNotFoundError,
  ExternalServerError,
  NetworkComputeRotationError,
  NetworkComputeAnalysisFailedError,
  NetworkComputeBridgeClient,
  PayloadClient,
  PayloadRegistrationResponseError,
  InvalidPayloadCredentialsError,
  PayloadNotAuthorizedError,
  PayloadAlreadyExistsError,
  PayloadDoesNotExistError,
  PayloadRegistrationClient,
  PayloadRegistrationKeepAlive,
  PayloadSoftwareUpdate,
  PayloadSoftwareUpdateClient,
  PayloadSoftwareUpdateInitiation,
  PayloadSoftwareUpdateInitiationClient,
  PointCloudClient,
  buildPcRequest,
  PointCloudResponseError,
  UnknownPointCloudSourceError,
  PointCloudDataError,
  PointCloudTypeError,
  PowerResponseError,
  ShorePowerConnectedError,
  BatteryMissingError,
  CommandInProgressError,
  EstoppedError,
  OverriddenError,
  KeepaliveMotorsOffError,
  FaultedError,
  FanControlTemperatureError,
  SafetyStopIncompatibleHardwareError,
  SafetyStopFailedError,
  SafetyStopUnknownStopTypeError,
  PowerError,
  PowerClient,
  powerOn,
  powerOff,
  powerOnMotors,
  powerOffMotors,
  safePowerOffRobot,
  safePowerOffMotors,
  powerOffRobot,
  safePowerCycleRobot,
  powerCycleRobot,
  safeSoftRebootRobot,
  softRebootRobot,
  powerOffPayloadPorts,
  powerOnPayloadPorts,
  powerOffWifiRadio,
  powerOnWifiRadio,
  isPoweredOn,
  AddRequestHeader,
  DataBufferLoggingProcessor,
  logAllRpcs,
  RayCastClient,
  RayCastResponseError,
  InvalidIntersectionTypeError,
  WaypointRegion,
  GraphNavRecordingServiceClient,
  RecordingServiceResponseError,
  CouldNotCreateWaypointError,
  NotRecordingError,
  EdgeExistsError,
  EdgeMissingTransformError,
  NotLocalizedToEndError,
  FollowingRouteError,
  NotLocalizedToExistingMapError,
  TooFarFromExistingMapError,
  RemoteCloudFailureNotInDirectoryError,
  RemoteCloudFailureNoDataError,
  NotReadyYetError,
  MissingFiducialsError,
  FiducialPoseError,
  RobotError,
  UnregisteredServiceError,
  UnregisteredServiceNameError,
  UnregisteredServiceTypeError,
  Robot,
  EDIT_TREE_CONVERT_LOCAL_TIME_TO_ROBOT_TIME,
  END_TIME_EDIT_TREE,
  RobotCommandResponseError,
  ExpiredError,
  NotPoweredOnError,
  BehaviorFaultError,
  DockedError,
  NotClearedError,
  UnsupportedError,
  CommandFailedError,
  CommandFailedErrorWithFeedback,
  RobotCommandClient,
  RobotCommandBuilder,
  RobotCommandStreamingClient,
  blockingCommand,
  blockingStand,
  blockingSit,
  blockingSelfright,
  blockUntilArmArrives,
  blockForTrajectoryCmd,
  RobotIdClient,
  compareVersions,
  toVersionArray,
  versionTuple,
  RobotStateClient,
  RobotStateStreamingClient,
  hasArm,
  generateClientName,
  createStandardSdk,
  BOSDYN_RESOURCE_ROOT,
  BOSDYN_CA_CERT_ENV,
  Sdk,
  SdkError,
  UnsetAppTokenError,
  UnableToLoadAppTokenError,
  GrpcServiceRunner,
  ResponseContext,
  populateResponseHeader,
  stripLargeBytesFields,
  getBytesFieldAllowlist,
  stripImageResponse,
  stripGetImageResponse,
  stripLocalGridResponses,
  stripStoreImageRequest,
  stripStoreDataRequest,
  stripRecordSignalTick,
  stripRecordDataBlob,
  InvalidCustomParamSpecError,
  InvalidCustomParamValueError,
  checkTypesMatch,
  validateDictSpec,
  createValueValidator,
  dictParamsToDict,
  listParamsToList,
  oneofParamToDict,
  customSpecToDefault,
  dictSpecToDefault,
  listSpecToDefault,
  intSpecToDefault,
  doubleSpecToDefault,
  stringSpecToDefault,
  roiSpecToDefault,
  boolSpecToDefault,
  oneOfSpecToDefault,
  dictParamCoerceTo,
  listParamCoerceTo,
  intParamCoerceTo,
  doubleParamCoerceTo,
  stringParamCoerceTo,
  roiParamCoerceTo,
  oneOfParamCoerceTo,
  customParamCoerceTo,
  makeCustomParamSpec,
  makeDictChildSpec,
  makeDictParamSpec,
  makeOneOfChildSpec,
  makeOneOfParamSpec,
  makeListParamSpec,
  makeInt64ParamSpec,
  makeDoubleParamSpec,
  makeStringParamSpec,
  makeBoolParamSpec,
  makeRegionOfInterestParamSpec,
  makeUserInterfaceInfo,
  makeRoiServiceAndSource,
  buildMaxAlertSpec,
  buildSimpleSignal,
  buildCapabilityLiveData,
  buildLiveDataResponse,
  getData,
  SpotCheckError,
  SpotCheckResponseError,
  SpotCheckUnexpectedPowerChangeError,
  SpotCheckImuCheckError,
  SpotCheckNotSittingError,
  SpotCheckLoadcellTimeoutError,
  SpotCheckPowerOnFailure,
  SpotCheckEndstopTimeoutError,
  SpotCheckStandFailureError,
  SpotCheckCameraTimeoutError,
  SpotCheckGroundCheckError,
  SpotCheckTimedOutError,
  CameraSpotCheckTimedOutError,
  CameraSpotCheckFeedbackError,
  CameraCalibrationResponseError,
  CameraCalibrationUserCanceledError,
  CameraCalibrationPowerError,
  CameraCalibrationTargetNotCenteredError,
  CameraCalibrationRobotCommandError,
  CameraCalibrationCalibrationError,
  CameraCalibrationInternalError,
  CameraCalibrationTimedOutError,
  SpotCheckClient,
  runSpotCheck,
  runCameraCalibration,
  TimeSyncError,
  NotEstablishedError,
  InactiveThreadError,
  TimeSyncClient,
  TimeSyncEndpoint,
  TimeSyncThread,
  timespecToRobotTimespan,
  robotTimeRangeFromDatetimes,
  robotTimeRangeFromNanoseconds,
  updateTimeFilter,
  updateTimestampFilter,
  TokenCache,
  TokenCacheFilesystem,
  TokenCacheError,
  ClearFailedError,
  NotInCacheError,
  WriteFailedError,
  TokenManager,
  USER_TOKEN_REFRESH_TIME_DELTA,
  USER_TOKEN_RETRY_INTERVAL_START,
  TEMPERATURES_NAMES,
  PRESSURE_NAMES,
  unitsToString,
  MAX_REDIRECTS,
  InterfaceNameNotFound,
  RequestError,
  Response,
  safeApiCall,
  validateUrl,
  checkOptions,
  cliLoginPrompt,
  cliAuth,
  authenticate,
  setupLogging,
  DedupLoggingMessages,
  doesDedupFilterExist,
  safePbEnumToString,
  getLogger,
  addCommonArguments,
  addCredentialsArguments,
  addBaseArguments,
  addPayloadCredentialsArguments,
  addPayloadCredentialsFileArgument,
  addServiceHostingArguments,
  addServiceEndpointArguments,
  readPayloadCredentials,
  readOrCreatePayloadCredentials,
  getGuidAndSecret,
  DefaultDict,
  polyfillDispose,
  buildProtoIndex,
  getProtoTypeName,
  protoTypeName,
  httpsGetUnverified,
  WorldObjectClient,
  makeAddWorldObjectReq,
  makeDeleteWorldObjectReq,
  makeChangeWorldObjectReq,
  sendAddMutationRequests,
  sendDeleteMutationRequests,
  BaseDataReader,
  BlockWriter,
  MessageChannel,
  TypedMessageChannel,
  GrpcRequests,
  GrpcResponses,
  MAGIC,
  END_MAGIC,
  BLOCK_HEADER_SIZE_MASK,
  BLOCK_HEADER_TYPE_MASK,
  DATA_BLOCK_TYPE,
  DESCRIPTOR_BLOCK_TYPE,
  END_BLOCK_TYPE,
  PROTOBUF_CONTENT_TYPE,
  SHA1_DIGEST_NBYTES,
  INDEX_OFFSET_OFFSET,
  LOGGER,
  POD_TYPE_TO_STRUCT,
  POD_TYPE_TO_NUM_BYTES,
  DataError,
  AddSeriesError,
  SeriesNotUniqueError,
  ChecksumError,
  DataFormatError,
  EOFError,
  SeriesIdentifier,
  packPodValues,
  unpackPodValues,
  DataReader,
  DataWriter,
  FileIndexer,
  GrpcProtoReader,
  GrpcReader,
  GrpcServiceReader,
  GrpcServiceWriter,
  MessageReader,
  PodSeriesReader,
  PodSeriesWriter,
  ProtobufChannelReader,
  ProtobufReader,
  ProtobufSeriesWriter,
  StreamDataReader,
  Event,
  EulerZXY,
  Lock,
  Queue,
  QueueFullError,
  TIME_FORMAT_DESC,
  RobotTimeConverter,
  distanceStr,
  formatFixed,
  formatMetric,
  setProcessName,
  secsToHms,
  timestampToDatetime,
  timestampToNsec,
  timestampToNsecBigInt,
  timestampToSec,
  toInt64String,
  toUint64String,
  getNanoSecTime,
  nsecToTimestamp,
  nowTimestamp,
  setTimestampFromDatetime,
  setTimestampFromNsec,
  setTimestampFromNow,
  setClockSource,
  systemTimeSec,
  nowNsec,
  nowMsec,
  nowSec,
  secToNsec,
  nsecToSec,
  secToMsec,
  msecToSec,
  timestampStr,
  durationToSeconds,
  durationStr,
  sum,
  accumulate,
  slice,
  secondsToDuration,
  secondsToTimestamp,
  parseTimespan,
  parseDatetime,
  DatetimeParseError,
  MissionClient,
  MissionResponseError,
  InvalidQuestionId,
  InvalidAnswerCode,
  QuestionAlreadyAnswered,
  CustomParamsError,
  IncompatibleAnswer,
  NoMissionError,
  NoMissionPlayingError,
  Result,
  CompileError,
  UnknownType,
  MissingParameterError,
  InaccessibleParameterError,
  MessageOverrideError,
  NodeUnreferenceableError,
  RemoteClient,
  InvalidSessionId,
  MissingInputs,
  MissingLeases,
  treeStatusFromTickStatus,
  DUMMY_MESSAGE,
  InvalidConversion,
  treeToString,
  typeToFieldName,
  protoFromObject,
  jsVarToValue,
  jsTypeToPbType,
  jsTypeToVariableDeclInfo,
  jsVarToVariableDecl,
  severityToLogLevel,
  isStringIdentifier,
  fieldDescToPbType,
  safePbTypeToString,
  oneLineStr,
  nodeSpecToShortString,
  ResultFromProto,
  protoEnumToResultConstant,
  resultConstantToProtoEnum,
  mostRestrictiveTravelParams,
  getValueFromConstantValueMessage,
  getValueFromValueMessage,
  createValue,
  defineBlackboard,
  setBlackboard,
  descriptorPool,
  gps,
  imageUtil,
  jsonFormat,
  orbit,
  spotCam,
  textFormat,
  alertsPb,
  authPb,
};
